####################################################
# Udacity Project 2 - Deploy WebApp Cloudformation #
####################################################

Description: >
  Author: Nicolas Neuburger / Udacity Nanodegree Cloud DevOps Engineer
  Purpose: > Project 2 - Deployment WebApp using CloudFormation
            > Contains cloudformation configuration for the cloud's permissions


Parameters:
  EnvironmentName:
      Description: An environment name that will be prefixed to resou
      Type: String
      Default: UdacityProject

Resources:

  JenkinsServerIamRole:
      Type: AWS::IAM::Role
      Properties:
          RoleName: !Join ["", [!Sub "${AWS::Region}", "JenkinsServerIamRole"]]
          AssumeRolePolicyDocument:
              Statement:
              - Action: ['sts:AssumeRole']
                Effect: Allow
                Principal:
                    Service: [ec2.amazonaws.com]
          Policies:
              - PolicyName: "FullAccessEC2"
                PolicyDocument:
                    Statement:
                    - Action:
                        - "ec2:*"
                      Effect: Allow
                      Resource: "*"
              - PolicyName: "FullAccessS3"
                PolicyDocument:
                    Statement:
                    - Action:
                        - "s3:*"
                      Effect: Allow
                      Resource: "*"


  JenkinsServerIamProfile:
      Type: AWS::IAM::InstanceProfile
      DependsOn: JenkinsServerIamRole
      Properties:
          Roles:
              - !Join ["", [!Sub "${AWS::Region}", "JenkinsServerIamRole"]]

Outputs:
  JenkinsServerIamProfile:
      Description: IAM Instance Profile defined for the WebApp to contact S3 services
      Value: !Ref JenkinsServerIamProfile
      Export:
        Name: !Sub "${EnvironmentName}-IAM-INST-APP"
  JenkinsServerIamProfile:
      Description: ARN of IAM Instance Profile defined for the WebApp to contact S3 services
      Value: !GetAtt "JenkinsServerIamProfile.Arn"
      Export:
        Name: !Sub "${EnvironmentName}-IAM-INST-APP-ARN"
